theme: jekyll-theme-cayman
title: zcd
description: 项目&随笔
show_downloads: true
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]