theme: jekyll-theme-cayman
site:
  title: zengcd
description: ht
show_downloads: true
page:
  title: zengcd
markdown: redcarpet
extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]